package Camera

import (
	"encoding/json"
	"log"
	"os"
)

// Generated by https://quicktype.io

type Material []MaterialElement

type MaterialElement struct {
	Shininess int     `json:"Shininess"`
	Specular  Ambient `json:"Specular"`
	Material  string  `json:"Material"`
	Diffuse   Ambient `json:"Diffuse"`
	Ambient   Ambient `json:"Ambient"`
}

type Ambient struct {
	B float32 `json:"B"`
	R float32 `json:"R"`
	G float32 `json:"G"`
}

func LoadMaterial(materialDescriptor string) Material {
	materialFile, err := os.Open(materialDescriptor)
	if err != nil {
		log.Println("Error opening material file:", err)
		os.Exit(127)
	}

	material := Material{}

	decoder := json.NewDecoder(materialFile)
	decoder.Decode(&material)

	log.Println(material)

	return material
}
